services:
  # Spring Boot Backend API Web Service
  - type: web
    name: skill-gap-backend-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: skill-gap-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: skill-gap-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: skill-gap-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: skill-gap-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: skill-gap-db
          property: password

  # React Frontend Static Site
  - type: web
    name: skill-gap-frontend-service
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://skill-gap-backend-service-itye.onrender.com

databases:
  - name: skill-gap-db
    plan: free
