services:
  # Spring Boot Backend API Web Service
  - type: web
    name: skill-gap-backend-service
    runtime: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
